from . import calendar
from . import markant_crm
from . import markant_partner
from . import markant_users
from . import crm_claim_line
from . import crm_claim
from . import sale_order_line
from . import sale_order
from . import res_groups
from . import trouble_responsible
from . import voip_phonecall
from . import report_sale_person_email_automation
