from . import webshop_attribute
from . import product_attribute
from . import webshop_product_tags
from . import product_brand
from . import file_extension_config
from . import product_template
from . import regular_attribute
from . import webshop_api_config
from . import product_pricelist
from . import res_partner
from . import webshop_delivery
from . import pcf_lookup
