from . import product_attribute
from . import product_template
from . import sale_product_configurator
from . import product_config_steps
from . import res_company
from . import mrp_bom
from . import stock_rule
from . import pcf_lookup
from . import ir_translation
