from . import product_template
from . import sale
from . import stock_move
from . import stock_rule
from . import stock_picking
from . import reserve_sale_picking
from . import sale_make_invoice_advance
from . import auto_invoice_log
from . import auto_invoice_mail
from . import product_strategy
from . import ir_actions_report
from . import stock_packaging
from . import picking_packaging
from . import res_company
from . import cost_price_computation_log
from . import res_config_settings
from . import ir_cron
